version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  application:
    container_name: car_dealer_backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:4000
    depends_on:
      - database
