version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  application:
    container_name: car_dealer_backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@postgres_db:5432/database
    ports:
      - 4001:4000
    depends_on:
      - database
