version: '3.8'

services:
  database:
    container_name: postgres_db_test
    image: postgres:latest
    restart: 'on-failure'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  application:
    container_name: car_dealer_backend_test
    build:
      context: ./
      dockerfile: Dockerfile.test
    restart: 'no'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:4000
    depends_on:
      - database
