FROM node:lts-alpine3.19 AS test
WORKDIR /app

COPY package.json ./
RUN yarn install --frozen-lockfile

COPY ./src ./src
COPY ./prisma ./prisma
COPY ./jest.config.js ./jest.config.js
COPY ./jest.integration.config.js ./jest.integration.config.js
COPY ./jest.unit.config.js ./jest.unit.config.js
COPY ./tsconfig.json ./tsconfig.json

RUN npx prisma generate

EXPOSE 4000
CMD ["yarn", "start:test"]
