version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  application:
    container_name: car_dealer_backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      PORT: 4001
      DATABASE_URL: postgresql://postgres:postgres@postgres_db:5432/database
      AUTH_SECRET: secret
      AUTH_EXPIRES_IN_SECONDS: 900
      AUTH_REFRESH_SECRET: refresh_secret
      AUTH_REFRESH_EXPIRES_IN_SECONDS: 86400
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: user
      MAIL_PASSWORD: pass
      ENCRYPTION_SECRET: encryption_secret
    ports:
      - 4001:4001
    depends_on:
      - database
