import z from 'zod';

export const vehicleResponseSchema = z.object({
  vehicleId: z.string().uuid(),
  model: z.string(),
  year: z.number(),
  plate: z.string(),
  description: z.string().nullable(),
  price: z.number(),
  mileage: z.number().nullable(),
  color: z.string().nullable(),
  transmission: z.string().nullable(),
  fuelType: z.string().nullable(),
  doors: z.number().nullable(),
  seats: z.number().nullable(),
  horsepower: z.number().nullable(),
  torque: z.number().nullable(),
  driveTrain: z.string().nullable(),
  brand: z.object({
    brandId: z.string().uuid(),
    name: z.string(),
    imageUrl: z.string(),
    active: z.boolean(),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  category: z.object({
    categoryId: z.string().uuid(),
    name: z.string(),
    imageUrl: z.string(),
    active: z.boolean(),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
  active: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
  vehicleImages: z.array(z.string()),
  vehicleFeatures: z.array(z.string()),
});
